"""initial migration

Revision ID: 825967935374
Revises: 
Create Date: 2026-02-19 12:46:27.044644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825967935374'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('user')
    with op.batch_alter_table('booking_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_participants_booking_id'))
        batch_op.drop_index(batch_op.f('ix_booking_participants_farmer_id'))

    op.drop_table('booking_participants')
    op.drop_table('tractor')
    with op.batch_alter_table('booking_addons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_addons_booking'))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('total_base_price',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_addon_price',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('grand_total',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('surge_multiplier',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('commission_pct',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('(10)'))
        batch_op.alter_column('commission_amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('owner_payout_amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('en_route_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('farmer_confirmed_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_bookings_owner_status'))
        batch_op.drop_column('shared_group_code')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_booking'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_owner'))

    with op.batch_alter_table('tractors', schema=None) as batch_op:
        batch_op.alter_column('equipment_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=24),
               existing_nullable=False,
               existing_server_default=sa.text("'Tractor'"))
        batch_op.alter_column('availability_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=24),
               existing_nullable=False,
               existing_server_default=sa.text("'available'"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_verified_owner',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('last_login',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('uq_users_phone_farmer'), sqlite_where=sa.text("lower(role)='farmer'"))
        batch_op.create_index(batch_op.f('ix_users_is_verified_owner'), ['is_verified_owner'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_verified_owner'))
        batch_op.create_index(batch_op.f('uq_users_phone_farmer'), ['phone'], unique=1, sqlite_where=sa.text("lower(role)='farmer'"))
        batch_op.alter_column('last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('is_verified_owner',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('tractors', schema=None) as batch_op:
        batch_op.alter_column('availability_status',
               existing_type=sa.String(length=24),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'available'"))
        batch_op.alter_column('equipment_type',
               existing_type=sa.String(length=24),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'Tractor'"))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_owner'), ['owner_id'], unique=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_booking'), ['booking_id', 'created_at'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_group_code', sa.TEXT(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bookings_owner_status'), ['owner_id', 'status'], unique=False)
        batch_op.alter_column('farmer_confirmed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('en_route_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('owner_payout_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('commission_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('commission_pct',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(10)'))
        batch_op.alter_column('surge_multiplier',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('grand_total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_addon_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_base_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('booking_addons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_addons_booking'), ['booking_id'], unique=False)

    op.create_table('tractor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price_per_hour', sa.FLOAT(), nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_participants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('booking_id', sa.INTEGER(), nullable=False),
    sa.Column('farmer_id', sa.INTEGER(), nullable=False),
    sa.Column('split_amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'farmer_id', name=op.f('uq_booking_participant'))
    )
    with op.batch_alter_table('booking_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_participants_farmer_id'), ['farmer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_participants_booking_id'), ['booking_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=200), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('booking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hours', sa.FLOAT(), nullable=True),
    sa.Column('fuel', sa.FLOAT(), nullable=True),
    sa.Column('co2', sa.FLOAT(), nullable=True),
    sa.Column('farmer_id', sa.INTEGER(), nullable=True),
    sa.Column('tractor_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tractor_id'], ['tractor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
